---
name: {{NAME}}
env: {{ENV}}

wredis_dsn: "{{REDIS_DSN}}"
images_path: {{IMAGES_PATH}}
images:
  single:
    - name: band-base
      runnable: false
      path: "{{BASE_IMG_PATH|default(IMAGES_PATH+'/band_base')}}"
  collection:
    path: "{{IMAGES_PATH}}/band_collection"
  user:
    path: "{{USER_IMAGES_PATH}}"

container_params:
  network: "{{NETWORK|default('custom')}}"
  memory: 367001600 # limit 350mb
  bind_ip: "{{BIND_HOST_IP}}"
container_env:
  REDIS_DSN: "{{REDIS_DSN}}"
  CH_DSN: "{{CH_DSN}}"
  CHS_DSN: "{{CHS_DSN}}"
  STATSD_HOST: "{{STATSD_HOST}}"
  JSON_LOGS: "{{JSON_LOGS}}"
