---
name: {{ NAME }}
env: {{ ENV }}

bind_addr: {{ HOST|default('0.0.0.0') }}
http_port: {{ PORT|default('8080') }}
redis_dsn: {{ REDIS_DSN|default('redis://127.16.25.1') }}
band_url: {{ BAND_URL|default('http://172.16.25.1:10000') }}

proxy_checker:
  list: {{ENDPOINT_PROXY_LIST}}
  regions: {{ENDPOINT_REGION_LIST}}
  auth: {{ENDPOINT_AUTH}}
  notify: {{PROXY_CHECK_NOTIFY}}

rucaptcha_key: {{RUCAPTCHA_KEY}}